# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads_v5/proto/services/topic_view_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.google_ads.v5.proto.resources import topic_view_pb2 as google_dot_ads_dot_googleads__v5_dot_proto_dot_resources_dot_topic__view__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import client_pb2 as google_dot_api_dot_client__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/ads/googleads_v5/proto/services/topic_view_service.proto',
  package='google.ads.googleads.v5.services',
  syntax='proto3',
  serialized_options=b'\n$com.google.ads.googleads.v5.servicesB\025TopicViewServiceProtoP\001ZHgoogle.golang.org/genproto/googleapis/ads/googleads/v5/services;services\242\002\003GAA\252\002 Google.Ads.GoogleAds.V5.Services\312\002 Google\\Ads\\GoogleAds\\V5\\Services\352\002$Google::Ads::GoogleAds::V5::Services',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?google/ads/googleads_v5/proto/services/topic_view_service.proto\x12 google.ads.googleads.v5.services\x1a\x38google/ads/googleads_v5/proto/resources/topic_view.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"X\n\x13GetTopicViewRequest\x12\x41\n\rresource_name\x18\x01 \x01(\tB*\xe0\x41\x02\xfa\x41$\n\"googleads.googleapis.com/TopicView2\xeb\x01\n\x10TopicViewService\x12\xb9\x01\n\x0cGetTopicView\x12\x35.google.ads.googleads.v5.services.GetTopicViewRequest\x1a,.google.ads.googleads.v5.resources.TopicView\"D\x82\xd3\xe4\x93\x02.\x12,/v5/{resource_name=customers/*/topicViews/*}\xda\x41\rresource_name\x1a\x1b\xca\x41\x18googleads.googleapis.comB\xfc\x01\n$com.google.ads.googleads.v5.servicesB\x15TopicViewServiceProtoP\x01ZHgoogle.golang.org/genproto/googleapis/ads/googleads/v5/services;services\xa2\x02\x03GAA\xaa\x02 Google.Ads.GoogleAds.V5.Services\xca\x02 Google\\Ads\\GoogleAds\\V5\\Services\xea\x02$Google::Ads::GoogleAds::V5::Servicesb\x06proto3'
  ,
  dependencies=[google_dot_ads_dot_googleads__v5_dot_proto_dot_resources_dot_topic__view__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_api_dot_client__pb2.DESCRIPTOR,google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,google_dot_api_dot_resource__pb2.DESCRIPTOR,])




_GETTOPICVIEWREQUEST = _descriptor.Descriptor(
  name='GetTopicViewRequest',
  full_name='google.ads.googleads.v5.services.GetTopicViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_name', full_name='google.ads.googleads.v5.services.GetTopicViewRequest.resource_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\002\372A$\n\"googleads.googleapis.com/TopicView', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=362,
)

DESCRIPTOR.message_types_by_name['GetTopicViewRequest'] = _GETTOPICVIEWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetTopicViewRequest = _reflection.GeneratedProtocolMessageType('GetTopicViewRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTOPICVIEWREQUEST,
  '__module__' : 'google.ads.googleads_v5.proto.services.topic_view_service_pb2'
  ,
  '__doc__': """Request message for [TopicViewService.GetTopicView][google.ads.googlea
  ds.v5.services.TopicViewService.GetTopicView].
  
  Attributes:
      resource_name:
          Required. The resource name of the topic view to fetch.
  """,
  # @@protoc_insertion_point(class_scope:google.ads.googleads.v5.services.GetTopicViewRequest)
  })
_sym_db.RegisterMessage(GetTopicViewRequest)


DESCRIPTOR._options = None
_GETTOPICVIEWREQUEST.fields_by_name['resource_name']._options = None

_TOPICVIEWSERVICE = _descriptor.ServiceDescriptor(
  name='TopicViewService',
  full_name='google.ads.googleads.v5.services.TopicViewService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=b'\312A\030googleads.googleapis.com',
  create_key=_descriptor._internal_create_key,
  serialized_start=365,
  serialized_end=600,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTopicView',
    full_name='google.ads.googleads.v5.services.TopicViewService.GetTopicView',
    index=0,
    containing_service=None,
    input_type=_GETTOPICVIEWREQUEST,
    output_type=google_dot_ads_dot_googleads__v5_dot_proto_dot_resources_dot_topic__view__pb2._TOPICVIEW,
    serialized_options=b'\202\323\344\223\002.\022,/v5/{resource_name=customers/*/topicViews/*}\332A\rresource_name',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOPICVIEWSERVICE)

DESCRIPTOR.services_by_name['TopicViewService'] = _TOPICVIEWSERVICE

# @@protoc_insertion_point(module_scope)
