# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads/v6/resources/payments_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/ads/googleads/v6/resources/payments_account.proto',
  package='google.ads.googleads.v6.resources',
  syntax='proto3',
  serialized_options=b'\n%com.google.ads.googleads.v6.resourcesB\024PaymentsAccountProtoP\001ZJgoogle.golang.org/genproto/googleapis/ads/googleads/v6/resources;resources\242\002\003GAA\252\002!Google.Ads.GoogleAds.V6.Resources\312\002!Google\\Ads\\GoogleAds\\V6\\Resources\352\002%Google::Ads::GoogleAds::V6::Resources',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8google/ads/googleads/v6/resources/payments_account.proto\x12!google.ads.googleads.v6.resources\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1cgoogle/api/annotations.proto\"\xdb\x04\n\x0fPaymentsAccount\x12G\n\rresource_name\x18\x01 \x01(\tB0\xe0\x41\x03\xfa\x41*\n(googleads.googleapis.com/PaymentsAccount\x12%\n\x13payments_account_id\x18\x08 \x01(\tB\x03\xe0\x41\x03H\x00\x88\x01\x01\x12\x16\n\x04name\x18\t \x01(\tB\x03\xe0\x41\x03H\x01\x88\x01\x01\x12\x1f\n\rcurrency_code\x18\n \x01(\tB\x03\xe0\x41\x03H\x02\x88\x01\x01\x12%\n\x13payments_profile_id\x18\x0b \x01(\tB\x03\xe0\x41\x03H\x03\x88\x01\x01\x12/\n\x1dsecondary_payments_profile_id\x18\x0c \x01(\tB\x03\xe0\x41\x03H\x04\x88\x01\x01\x12O\n\x17paying_manager_customer\x18\r \x01(\tB)\xe0\x41\x03\xfa\x41#\n!googleads.googleapis.com/CustomerH\x05\x88\x01\x01:m\xea\x41j\n(googleads.googleapis.com/PaymentsAccount\x12>customers/{customer_id}/paymentsAccounts/{payments_account_id}B\x16\n\x14_payments_account_idB\x07\n\x05_nameB\x10\n\x0e_currency_codeB\x16\n\x14_payments_profile_idB \n\x1e_secondary_payments_profile_idB\x1a\n\x18_paying_manager_customerB\x81\x02\n%com.google.ads.googleads.v6.resourcesB\x14PaymentsAccountProtoP\x01ZJgoogle.golang.org/genproto/googleapis/ads/googleads/v6/resources;resources\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V6.Resources\xca\x02!Google\\Ads\\GoogleAds\\V6\\Resources\xea\x02%Google::Ads::GoogleAds::V6::Resourcesb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,google_dot_api_dot_resource__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_PAYMENTSACCOUNT = _descriptor.Descriptor(
  name='PaymentsAccount',
  full_name='google.ads.googleads.v6.resources.PaymentsAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_name', full_name='google.ads.googleads.v6.resources.PaymentsAccount.resource_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003\372A*\n(googleads.googleapis.com/PaymentsAccount', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payments_account_id', full_name='google.ads.googleads.v6.resources.PaymentsAccount.payments_account_id', index=1,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='google.ads.googleads.v6.resources.PaymentsAccount.name', index=2,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currency_code', full_name='google.ads.googleads.v6.resources.PaymentsAccount.currency_code', index=3,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payments_profile_id', full_name='google.ads.googleads.v6.resources.PaymentsAccount.payments_profile_id', index=4,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='secondary_payments_profile_id', full_name='google.ads.googleads.v6.resources.PaymentsAccount.secondary_payments_profile_id', index=5,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='paying_manager_customer', full_name='google.ads.googleads.v6.resources.PaymentsAccount.paying_manager_customer', index=6,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003\372A#\n!googleads.googleapis.com/Customer', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\352Aj\n(googleads.googleapis.com/PaymentsAccount\022>customers/{customer_id}/paymentsAccounts/{payments_account_id}',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_payments_account_id', full_name='google.ads.googleads.v6.resources.PaymentsAccount._payments_account_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='google.ads.googleads.v6.resources.PaymentsAccount._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_currency_code', full_name='google.ads.googleads.v6.resources.PaymentsAccount._currency_code',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_payments_profile_id', full_name='google.ads.googleads.v6.resources.PaymentsAccount._payments_profile_id',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_secondary_payments_profile_id', full_name='google.ads.googleads.v6.resources.PaymentsAccount._secondary_payments_profile_id',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_paying_manager_customer', full_name='google.ads.googleads.v6.resources.PaymentsAccount._paying_manager_customer',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=186,
  serialized_end=789,
)

_PAYMENTSACCOUNT.oneofs_by_name['_payments_account_id'].fields.append(
  _PAYMENTSACCOUNT.fields_by_name['payments_account_id'])
_PAYMENTSACCOUNT.fields_by_name['payments_account_id'].containing_oneof = _PAYMENTSACCOUNT.oneofs_by_name['_payments_account_id']
_PAYMENTSACCOUNT.oneofs_by_name['_name'].fields.append(
  _PAYMENTSACCOUNT.fields_by_name['name'])
_PAYMENTSACCOUNT.fields_by_name['name'].containing_oneof = _PAYMENTSACCOUNT.oneofs_by_name['_name']
_PAYMENTSACCOUNT.oneofs_by_name['_currency_code'].fields.append(
  _PAYMENTSACCOUNT.fields_by_name['currency_code'])
_PAYMENTSACCOUNT.fields_by_name['currency_code'].containing_oneof = _PAYMENTSACCOUNT.oneofs_by_name['_currency_code']
_PAYMENTSACCOUNT.oneofs_by_name['_payments_profile_id'].fields.append(
  _PAYMENTSACCOUNT.fields_by_name['payments_profile_id'])
_PAYMENTSACCOUNT.fields_by_name['payments_profile_id'].containing_oneof = _PAYMENTSACCOUNT.oneofs_by_name['_payments_profile_id']
_PAYMENTSACCOUNT.oneofs_by_name['_secondary_payments_profile_id'].fields.append(
  _PAYMENTSACCOUNT.fields_by_name['secondary_payments_profile_id'])
_PAYMENTSACCOUNT.fields_by_name['secondary_payments_profile_id'].containing_oneof = _PAYMENTSACCOUNT.oneofs_by_name['_secondary_payments_profile_id']
_PAYMENTSACCOUNT.oneofs_by_name['_paying_manager_customer'].fields.append(
  _PAYMENTSACCOUNT.fields_by_name['paying_manager_customer'])
_PAYMENTSACCOUNT.fields_by_name['paying_manager_customer'].containing_oneof = _PAYMENTSACCOUNT.oneofs_by_name['_paying_manager_customer']
DESCRIPTOR.message_types_by_name['PaymentsAccount'] = _PAYMENTSACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaymentsAccount = _reflection.GeneratedProtocolMessageType('PaymentsAccount', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTSACCOUNT,
  '__module__' : 'google.ads.googleads.v6.resources.payments_account_pb2'
  # @@protoc_insertion_point(class_scope:google.ads.googleads.v6.resources.PaymentsAccount)
  })
_sym_db.RegisterMessage(PaymentsAccount)


DESCRIPTOR._options = None
_PAYMENTSACCOUNT.fields_by_name['resource_name']._options = None
_PAYMENTSACCOUNT.fields_by_name['payments_account_id']._options = None
_PAYMENTSACCOUNT.fields_by_name['name']._options = None
_PAYMENTSACCOUNT.fields_by_name['currency_code']._options = None
_PAYMENTSACCOUNT.fields_by_name['payments_profile_id']._options = None
_PAYMENTSACCOUNT.fields_by_name['secondary_payments_profile_id']._options = None
_PAYMENTSACCOUNT.fields_by_name['paying_manager_customer']._options = None
_PAYMENTSACCOUNT._options = None
# @@protoc_insertion_point(module_scope)
