# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads_v6/proto/resources/user_interest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.ads.google_ads.v6.proto.common import criterion_category_availability_pb2 as google_dot_ads_dot_googleads__v6_dot_proto_dot_common_dot_criterion__category__availability__pb2
from google.ads.google_ads.v6.proto.enums import user_interest_taxonomy_type_pb2 as google_dot_ads_dot_googleads__v6_dot_proto_dot_enums_dot_user__interest__taxonomy__type__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.api import resource_pb2 as google_dot_api_dot_resource__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/ads/googleads_v6/proto/resources/user_interest.proto',
  package='google.ads.googleads.v6.resources',
  syntax='proto3',
  serialized_options=b'\n%com.google.ads.googleads.v6.resourcesB\021UserInterestProtoP\001ZJgoogle.golang.org/genproto/googleapis/ads/googleads/v6/resources;resources\242\002\003GAA\252\002!Google.Ads.GoogleAds.V6.Resources\312\002!Google\\Ads\\GoogleAds\\V6\\Resources\352\002%Google::Ads::GoogleAds::V6::Resources',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n;google/ads/googleads_v6/proto/resources/user_interest.proto\x12!google.ads.googleads.v6.resources\x1aJgoogle/ads/googleads_v6/proto/common/criterion_category_availability.proto\x1a\x45google/ads/googleads_v6/proto/enums/user_interest_taxonomy_type.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x1cgoogle/api/annotations.proto\"\x84\x05\n\x0cUserInterest\x12\x44\n\rresource_name\x18\x01 \x01(\tB-\xe0\x41\x03\xfa\x41\'\n%googleads.googleapis.com/UserInterest\x12p\n\rtaxonomy_type\x18\x02 \x01(\x0e\x32T.google.ads.googleads.v6.enums.UserInterestTaxonomyTypeEnum.UserInterestTaxonomyTypeB\x03\xe0\x41\x03\x12\"\n\x10user_interest_id\x18\x08 \x01(\x03\x42\x03\xe0\x41\x03H\x00\x88\x01\x01\x12\x16\n\x04name\x18\t \x01(\tB\x03\xe0\x41\x03H\x01\x88\x01\x01\x12P\n\x14user_interest_parent\x18\n \x01(\tB-\xe0\x41\x03\xfa\x41\'\n%googleads.googleapis.com/UserInterestH\x02\x88\x01\x01\x12!\n\x0flaunched_to_all\x18\x0b \x01(\x08\x42\x03\xe0\x41\x03H\x03\x88\x01\x01\x12Z\n\x0e\x61vailabilities\x18\x07 \x03(\x0b\x32=.google.ads.googleads.v6.common.CriterionCategoryAvailabilityB\x03\xe0\x41\x03:d\xea\x41\x61\n%googleads.googleapis.com/UserInterest\x12\x38\x63ustomers/{customer_id}/userInterests/{user_interest_id}B\x13\n\x11_user_interest_idB\x07\n\x05_nameB\x17\n\x15_user_interest_parentB\x12\n\x10_launched_to_allB\xfe\x01\n%com.google.ads.googleads.v6.resourcesB\x11UserInterestProtoP\x01ZJgoogle.golang.org/genproto/googleapis/ads/googleads/v6/resources;resources\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V6.Resources\xca\x02!Google\\Ads\\GoogleAds\\V6\\Resources\xea\x02%Google::Ads::GoogleAds::V6::Resourcesb\x06proto3'
  ,
  dependencies=[google_dot_ads_dot_googleads__v6_dot_proto_dot_common_dot_criterion__category__availability__pb2.DESCRIPTOR,google_dot_ads_dot_googleads__v6_dot_proto_dot_enums_dot_user__interest__taxonomy__type__pb2.DESCRIPTOR,google_dot_api_dot_field__behavior__pb2.DESCRIPTOR,google_dot_api_dot_resource__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_USERINTEREST = _descriptor.Descriptor(
  name='UserInterest',
  full_name='google.ads.googleads.v6.resources.UserInterest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_name', full_name='google.ads.googleads.v6.resources.UserInterest.resource_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003\372A\'\n%googleads.googleapis.com/UserInterest', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taxonomy_type', full_name='google.ads.googleads.v6.resources.UserInterest.taxonomy_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_interest_id', full_name='google.ads.googleads.v6.resources.UserInterest.user_interest_id', index=2,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='google.ads.googleads.v6.resources.UserInterest.name', index=3,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_interest_parent', full_name='google.ads.googleads.v6.resources.UserInterest.user_interest_parent', index=4,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003\372A\'\n%googleads.googleapis.com/UserInterest', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='launched_to_all', full_name='google.ads.googleads.v6.resources.UserInterest.launched_to_all', index=5,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='availabilities', full_name='google.ads.googleads.v6.resources.UserInterest.availabilities', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\340A\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\352Aa\n%googleads.googleapis.com/UserInterest\0228customers/{customer_id}/userInterests/{user_interest_id}',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_user_interest_id', full_name='google.ads.googleads.v6.resources.UserInterest._user_interest_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_name', full_name='google.ads.googleads.v6.resources.UserInterest._name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_user_interest_parent', full_name='google.ads.googleads.v6.resources.UserInterest._user_interest_parent',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_launched_to_all', full_name='google.ads.googleads.v6.resources.UserInterest._launched_to_all',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=336,
  serialized_end=980,
)

_USERINTEREST.fields_by_name['taxonomy_type'].enum_type = google_dot_ads_dot_googleads__v6_dot_proto_dot_enums_dot_user__interest__taxonomy__type__pb2._USERINTERESTTAXONOMYTYPEENUM_USERINTERESTTAXONOMYTYPE
_USERINTEREST.fields_by_name['availabilities'].message_type = google_dot_ads_dot_googleads__v6_dot_proto_dot_common_dot_criterion__category__availability__pb2._CRITERIONCATEGORYAVAILABILITY
_USERINTEREST.oneofs_by_name['_user_interest_id'].fields.append(
  _USERINTEREST.fields_by_name['user_interest_id'])
_USERINTEREST.fields_by_name['user_interest_id'].containing_oneof = _USERINTEREST.oneofs_by_name['_user_interest_id']
_USERINTEREST.oneofs_by_name['_name'].fields.append(
  _USERINTEREST.fields_by_name['name'])
_USERINTEREST.fields_by_name['name'].containing_oneof = _USERINTEREST.oneofs_by_name['_name']
_USERINTEREST.oneofs_by_name['_user_interest_parent'].fields.append(
  _USERINTEREST.fields_by_name['user_interest_parent'])
_USERINTEREST.fields_by_name['user_interest_parent'].containing_oneof = _USERINTEREST.oneofs_by_name['_user_interest_parent']
_USERINTEREST.oneofs_by_name['_launched_to_all'].fields.append(
  _USERINTEREST.fields_by_name['launched_to_all'])
_USERINTEREST.fields_by_name['launched_to_all'].containing_oneof = _USERINTEREST.oneofs_by_name['_launched_to_all']
DESCRIPTOR.message_types_by_name['UserInterest'] = _USERINTEREST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInterest = _reflection.GeneratedProtocolMessageType('UserInterest', (_message.Message,), {
  'DESCRIPTOR' : _USERINTEREST,
  '__module__' : 'google.ads.googleads_v6.proto.resources.user_interest_pb2'
  ,
  '__doc__': """A user interest: a particular interest-based vertical to be targeted.
  
  Attributes:
      resource_name:
          Output only. The resource name of the user interest. User
          interest resource names have the form:
          ``customers/{customer_id}/userInterests/{user_interest_id}``
      taxonomy_type:
          Output only. Taxonomy type of the user interest.
      user_interest_id:
          Output only. The ID of the user interest.
      name:
          Output only. The name of the user interest.
      user_interest_parent:
          Output only. The parent of the user interest.
      launched_to_all:
          Output only. True if the user interest is launched to all
          channels and locales.
      availabilities:
          Output only. Availability information of the user interest.
  """,
  # @@protoc_insertion_point(class_scope:google.ads.googleads.v6.resources.UserInterest)
  })
_sym_db.RegisterMessage(UserInterest)


DESCRIPTOR._options = None
_USERINTEREST.fields_by_name['resource_name']._options = None
_USERINTEREST.fields_by_name['taxonomy_type']._options = None
_USERINTEREST.fields_by_name['user_interest_id']._options = None
_USERINTEREST.fields_by_name['name']._options = None
_USERINTEREST.fields_by_name['user_interest_parent']._options = None
_USERINTEREST.fields_by_name['launched_to_all']._options = None
_USERINTEREST.fields_by_name['availabilities']._options = None
_USERINTEREST._options = None
# @@protoc_insertion_point(module_scope)
