# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/ads/googleads_v0/proto/enums/campaign_group_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/ads/googleads_v0/proto/enums/campaign_group_status.proto',
  package='google.ads.googleads.v0.enums',
  syntax='proto3',
  serialized_pb=_b('\n?google/ads/googleads_v0/proto/enums/campaign_group_status.proto\x12\x1dgoogle.ads.googleads.v0.enums\"h\n\x17\x43\x61mpaignGroupStatusEnum\"M\n\x13\x43\x61mpaignGroupStatus\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x0b\n\x07\x45NABLED\x10\x02\x12\x0b\n\x07REMOVED\x10\x04\x42\xc9\x01\n!com.google.ads.googleads.v0.enumsB\x18\x43\x61mpaignGroupStatusProtoP\x01ZBgoogle.golang.org/genproto/googleapis/ads/googleads/v0/enums;enums\xa2\x02\x03GAA\xaa\x02\x1dGoogle.Ads.GoogleAds.V0.Enums\xca\x02\x1dGoogle\\Ads\\GoogleAds\\V0\\Enumsb\x06proto3')
)



_CAMPAIGNGROUPSTATUSENUM_CAMPAIGNGROUPSTATUS = _descriptor.EnumDescriptor(
  name='CampaignGroupStatus',
  full_name='google.ads.googleads.v0.enums.CampaignGroupStatusEnum.CampaignGroupStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENABLED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMOVED', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=125,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_CAMPAIGNGROUPSTATUSENUM_CAMPAIGNGROUPSTATUS)


_CAMPAIGNGROUPSTATUSENUM = _descriptor.Descriptor(
  name='CampaignGroupStatusEnum',
  full_name='google.ads.googleads.v0.enums.CampaignGroupStatusEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CAMPAIGNGROUPSTATUSENUM_CAMPAIGNGROUPSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=202,
)

_CAMPAIGNGROUPSTATUSENUM_CAMPAIGNGROUPSTATUS.containing_type = _CAMPAIGNGROUPSTATUSENUM
DESCRIPTOR.message_types_by_name['CampaignGroupStatusEnum'] = _CAMPAIGNGROUPSTATUSENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CampaignGroupStatusEnum = _reflection.GeneratedProtocolMessageType('CampaignGroupStatusEnum', (_message.Message,), dict(
  DESCRIPTOR = _CAMPAIGNGROUPSTATUSENUM,
  __module__ = 'google.ads.googleads_v0.proto.enums.campaign_group_status_pb2'
  ,
  __doc__ = """Message describing CampaignGroup statuses.
  """,
  # @@protoc_insertion_point(class_scope:google.ads.googleads.v0.enums.CampaignGroupStatusEnum)
  ))
_sym_db.RegisterMessage(CampaignGroupStatusEnum)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.google.ads.googleads.v0.enumsB\030CampaignGroupStatusProtoP\001ZBgoogle.golang.org/genproto/googleapis/ads/googleads/v0/enums;enums\242\002\003GAA\252\002\035Google.Ads.GoogleAds.V0.Enums\312\002\035Google\\Ads\\GoogleAds\\V0\\Enums'))
# @@protoc_insertion_point(module_scope)
